<?php

namespace models\ODM\Repositories;

use Doctrine\ODM\MongoDB\DocumentRepository;
use DateTime;
use lib\Core\Manager;

/**
 * AdminRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminRepository extends DocumentRepository {

  /**
   * @static
   * @return \models\ODM\Repositories\AdminRepository
   */
  static public function getRepository(){
    return \lib\Doctrine\DoctrineOdm::getRepository('Documents\Admin');
  }

  /**
   * @param \Documents\Admin $admin
   */
  public function createAdmin(\Documents\Admin $admin){

    $admin->setDate(new DateTime());
    $admin->setEnable(true);
    $admin->setIsActivated(true);
    $password = $admin->getPassword();

    $hash = Manager::$Crypt->create($password);

    $admin->setPassword($hash);

    $this->dm->persist($admin);
    $this->dm->flush();
  }

  /**
   * @param \Documents\Admin $admin
   */
  public function updateAdmin(\Documents\Admin $admin){

    $admin->setDate(time());

    $this->dm->persist($admin);
    $this->dm->flush();
  }

  /**
   * @param \Documents\Admin $admin
   */
  public function deleteAdmin(\Documents\Admin $admin){

    $this->dm->remove($admin);
    $this->dm->flush();
  }

}