<?php

namespace models\ODM\Repositories;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Documents\Shop\Products;
use lib\Doctrine\DoctrineOdm;

/**
 * ShopProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopProductsRepository extends DocumentRepository
{

  /**
    * @static
    * @return ShopProductsRepository
    */
   static public function getRepository(){
     return DoctrineOdm::getRepository('Documents\Shop\Products');
   }

   /**
    * @param Products $products
    */
   public function update(Products $products){

     $this->dm->persist($products);
     $this->dm->flush();
   }

   /**
    * @param Products $products
    */
   public function delete(Products $products){

     $this->dm->remove($products);
     $this->dm->flush();
   }

}