<?php

namespace models\ODM\Repositories;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ShopProductsTypesTreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopProductsTypesTreeRepository extends DocumentRepository
{

  /**
   * @static
   * @return \models\ODM\Repositories\ShopProductsTypesTreeRepository
   */
  static public function getRepository(){
    return \lib\Doctrine\DoctrineOdm::getRepository('Documents\Shop\ProductsTypesTree');
  }

}