<?php

namespace models\ODM\Repositories;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * ShopCatalogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopCatalogRepository extends DocumentRepository
{

  /**
   * @static
   * @return \models\ODM\Repositories\ShopCatalogRepository
   */
  static public function getRepository(){
    return \lib\Doctrine\DoctrineOdm::getRepository('Documents\Shop\Catalog');
  }

}