<?php

namespace models\ODM\Repositories;

use Doctrine\ODM\MongoDB\DocumentRepository;
use Documents\Shop\ProductsTypesProperty;

/**
 * ShopProductsTypesPropertyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopProductsTypesPropertyRepository extends DocumentRepository
{

  /**
   * @static
   * @return \models\ODM\Repositories\ShopProductsTypesPropertyRepository
   */
  static public function getRepository(){
    return \lib\Doctrine\DoctrineOdm::getRepository('Documents\Shop\ProductsTypesProperty');
  }

  /**
   * @param \Documents\Shop\ProductsTypesProperty $property
   */
  public function update(ProductsTypesProperty $property){

    $this->dm->persist($property);
    $this->dm->flush();
  }

  /**
   * @param \Documents\Shop\ProductsTypesProperty $property
   */
  public function add(ProductsTypesProperty $property){

    $this->dm->persist($property);
    $this->dm->flush();
  }

  /**
   * @param \Documents\Shop\ProductsTypesProperty $property
   */
  public function delete(ProductsTypesProperty $property){

    $this->dm->remove($property);
    $this->dm->flush();
  }

}